steps:
  # Access secrets and set them as environment variables
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "$$MONGODB_URI" > /workspace/mongodb_uri
        echo "$$MONGODB_DB" > /workspace/mongodb_db
        echo "$$GOOGLE_AI_API_KEY" > /workspace/google_ai_key
    secretEnv: ['MONGODB_URI', 'MONGODB_DB', 'GOOGLE_AI_API_KEY']

  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--cache-from'
      - 'asia-south1-docker.pkg.dev/${PROJECT_ID}/truthguard-repo/truthguard-frontend:latest'
      - '-t'
      - 'asia-south1-docker.pkg.dev/${PROJECT_ID}/truthguard-repo/truthguard-frontend:$COMMIT_SHA'
      - '-t'
      - 'asia-south1-docker.pkg.dev/${PROJECT_ID}/truthguard-repo/truthguard-frontend:latest'
      - '--build-arg'
      - 'MONGODB_URI=$(cat /workspace/mongodb_uri)'
      - '--build-arg'
      - 'MONGODB_DB=$(cat /workspace/mongodb_db)'
      - '--build-arg'
      - 'GOOGLE_AI_API_KEY=$(cat /workspace/google_ai_key)'
      - '--build-arg'
      - 'NEXT_PUBLIC_BASE_URL=http://backend:5000'
      - '.'
    id: 'Build'

  # Push the container images to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-south1-docker.pkg.dev/${PROJECT_ID}/truthguard-repo/truthguard-frontend:$COMMIT_SHA']
    id: 'Push SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-south1-docker.pkg.dev/${PROJECT_ID}/truthguard-repo/truthguard-frontend:latest']
    id: 'Push Latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'truthguard-frontend'
      - '--image'
      - 'asia-south1-docker.pkg.dev/${PROJECT_ID}/truthguard-repo/truthguard-frontend:$COMMIT_SHA'
      - '--region'
      - 'asia-south1'
      - '--platform'
      - 'managed'
      - '--port'
      - '8080'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '100'
      - '--timeout'
      - '300s'
      - '--concurrency'
      - '80'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'NODE_ENV=production,NEXT_TELEMETRY_DISABLED=1'
      - '--set-secrets'
      - 'MONGODB_URI=MONGODB_URI:latest,MONGODB_DB=MONGODB_DB:latest,GOOGLE_AI_API_KEY=GOOGLE_AI_API_KEY:latest'
    id: 'Deploy'

options:
  logging: CLOUD_LOGGING_ONLY
  dynamicSubstitutions: true

availableSecrets:
  secretManager:
    - versionName: projects/${PROJECT_ID}/secrets/MONGODB_URI/versions/latest
      env: 'MONGODB_URI'
    - versionName: projects/${PROJECT_ID}/secrets/MONGODB_DB/versions/latest
      env: 'MONGODB_DB'
    - versionName: projects/${PROJECT_ID}/secrets/GOOGLE_AI_API_KEY/versions/latest
      env: 'GOOGLE_AI_API_KEY'

images:
  - 'asia-south1-docker.pkg.dev/${PROJECT_ID}/truthguard-repo/truthguard-frontend:$COMMIT_SHA'
  - 'asia-south1-docker.pkg.dev/${PROJECT_ID}/truthguard-repo/truthguard-frontend:latest'

timeout: '1800s'
