steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'NEXT_PUBLIC_BASE_URL=https://truthguard-frontend-377368788327.asia-south1.run.app'
      - '--build-arg'
      - 'MONGODB_URI=$MONGODB_URI'
      - '--build-arg'
      - 'MONGODB_DB=$MONGODB_DB'
      - '--build-arg'
      - 'GOOGLE_AI_API_KEY=$GOOGLE_AI_API_KEY'
      - '--build-arg'
      - 'BACKEND_BASE_URL=$BACKEND_BASE_URL'
      - '-t'
      - 'asia-south1-docker.pkg.dev/constant-wonder-461912-n2/truthguard-repo/truthguard-frontend:$COMMIT_SHA'
      - '-t'
      - 'asia-south1-docker.pkg.dev/constant-wonder-461912-n2/truthguard-repo/truthguard-frontend:latest'
      - '.'
    secretEnv: ['MONGODB_URI', 'MONGODB_DB', 'GOOGLE_AI_API_KEY', 'BACKEND_BASE_URL']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-south1-docker.pkg.dev/constant-wonder-461912-n2/truthguard-repo/truthguard-frontend:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-south1-docker.pkg.dev/constant-wonder-461912-n2/truthguard-repo/truthguard-frontend:latest']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'truthguard-frontend'
      - '--image'
      - 'asia-south1-docker.pkg.dev/constant-wonder-461912-n2/truthguard-repo/truthguard-frontend:$COMMIT_SHA'
      - '--region'
      - 'asia-south1'
      - '--platform=managed'
      - '--port=8080'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--min-instances=0'
      - '--max-instances=100'
      - '--timeout=300s'
      - '--concurrency=80'
      - '--allow-unauthenticated'
      - '--set-secrets=MONGODB_URI=MONGODB_URI:latest,MONGODB_DB=MONGODB_DB:latest,GOOGLE_AI_API_KEY=GOOGLE_AI_API_KEY:latest,BACKEND_BASE_URL=BACKEND_BASE_URL:latest'

availableSecrets:
  secretManager:
    MONGODB_URI:
      versionName: projects/constant-wonder-461912-n2/secrets/MONGODB_URI/versions/latest
    MONGODB_DB:
      versionName: projects/constant-wonder-461912-n2/secrets/MONGODB_DB/versions/latest
    GOOGLE_AI_API_KEY:
      versionName: projects/constant-wonder-461912-n2/secrets/GOOGLE_AI_API_KEY/versions/latest
    BACKEND_BASE_URL:
      versionName: projects/constant-wonder-461912-n2/secrets/BACKEND_BASE_URL/versions/latest

images:
  - 'asia-south1-docker.pkg.dev/constant-wonder-461912-n2/truthguard-repo/truthguard-frontend:$COMMIT_SHA'
  - 'asia-south1-docker.pkg.dev/constant-wonder-461912-n2/truthguard-repo/truthguard-frontend:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  dynamicSubstitutions: true
timeout: '1800s'
