steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'NEXT_PUBLIC_MONGODB_URI=$NEXT_PUBLIC_MONGODB_URI'
      - '--build-arg'
      - 'NEXT_PUBLIC_MONGODB_DB=$NEXT_PUBLIC_MONGODB_DB'
      - '--build-arg'
      - 'NEXT_PUBLIC_GOOGLE_AI_API_KEY=$NEXT_PUBLIC_GOOGLE_AI_API_KEY'
      - '--build-arg'
      - 'NEXT_PUBLIC_BACKEND_BASE_URL=$NEXT_PUBLIC_BACKEND_BASE_URL'
      - '-t'
      - 'asia-south1-docker.pkg.dev/constant-wonder-461912-n2/truthguard-repo/truthguard-frontend:$COMMIT_SHA'
      - '-t'
      - 'asia-south1-docker.pkg.dev/constant-wonder-461912-n2/truthguard-repo/truthguard-frontend:latest'
      - '.'
    secretEnv: ['NEXT_PUBLIC_MONGODB_URI', 'NEXT_PUBLIC_MONGODB_DB', 'NEXT_PUBLIC_GOOGLE_AI_API_KEY', 'NEXT_PUBLIC_BACKEND_BASE_URL']

  # Push the images to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-south1-docker.pkg.dev/constant-wonder-461912-n2/truthguard-repo/truthguard-frontend:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-south1-docker.pkg.dev/constant-wonder-461912-n2/truthguard-repo/truthguard-frontend:latest']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'truthguard-frontend'
      - '--image'
      - 'asia-south1-docker.pkg.dev/constant-wonder-461912-n2/truthguard-repo/truthguard-frontend:latest'
      - '--region'
      - 'asia-south1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--update-secrets=NEXT_PUBLIC_MONGODB_URI=NEXT_PUBLIC_MONGODB_URI:latest'
      - '--update-secrets=NEXT_PUBLIC_MONGODB_DB=NEXT_PUBLIC_MONGODB_DB:latest'
      - '--update-secrets=NEXT_PUBLIC_GOOGLE_AI_API_KEY=NEXT_PUBLIC_GOOGLE_AI_API_KEY:latest'
      - '--update-secrets=NEXT_PUBLIC_BACKEND_BASE_URL=NEXT_PUBLIC_BACKEND_BASE_URL:latest'
      - '--set-env-vars=NODE_ENV=production'

# Make secrets available to all build steps from Secret Manager
availableSecrets:
  secretManager:
    - versionName: projects/constant-wonder-461912-n2/secrets/NEXT_PUBLIC_MONGODB_URI/versions/latest
      env: 'NEXT_PUBLIC_MONGODB_URI'
    - versionName: projects/constant-wonder-461912-n2/secrets/NEXT_PUBLIC_MONGODB_DB/versions/latest
      env: 'NEXT_PUBLIC_MONGODB_DB'
    - versionName: projects/constant-wonder-461912-n2/secrets/NEXT_PUBLIC_GOOGLE_AI_API_KEY/versions/latest
      env: 'NEXT_PUBLIC_GOOGLE_AI_API_KEY'
    - versionName: projects/constant-wonder-461912-n2/secrets/NEXT_PUBLIC_BACKEND_BASE_URL/versions/latest
      env: 'NEXT_PUBLIC_BACKEND_BASE_URL'

images:
  - 'asia-south1-docker.pkg.dev/constant-wonder-461912-n2/truthguard-repo/truthguard-frontend:$COMMIT_SHA'
  - 'asia-south1-docker.pkg.dev/constant-wonder-461912-n2/truthguard-repo/truthguard-frontend:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  dynamicSubstitutions: true
timeout: '1800s'